# (r) = changes require application restart

# Environment Variables
env:
 TERM: xterm-256color

# Import color scheme
import:
- "~/.config/alacritty/color.yml"

window:
  # Window dimensions in character columns and lines (r)
  dimensions:
    columns: 120
    lines: 61

  position:
    x: 920
    y: 30

  # Startup Mode (changes require restart)
  # Values for `startup_mode`:
  #   - Windowed
  #   - Maximized
  #   - Fullscreen
  # Values for `startup_mode` (macOS only):
  #   - SimpleFullscreen
  startup_mode: Windowed 

  # Adds this many blank pixels of padding around the window
  # Units are physical pixels; this is not DPI aware.
  # (change requires restart)
  padding:
    x: 10
    y: 10

  # Spread additional padding evenly around the terminal content.
  dynamic_padding: true

  dynamic_title: true

  # Background opacity
  # opacity: 1
  opacity: 0.85

  # Window decoration
  # Full, Transparent, Buttonless, None
  decorations: Buttonless

# When true, bold text is drawn using the bright variant of colors.
draw_bold_text_with_bright_colors: true

scrolling:
  # Maximum number of lines in the scrollback buffer.
  history: 100000
  # Number of lines the viewport will move for every line scrolled when scrollback is enabled. 
  multiplier: 1

# Font configuration (changes require restart)
font:
 # The normal (roman) font face to use.
  normal:
    family: FiraCode Nerd Font
    style: Regular
 
  # The bold font face
  bold:
    family: FiraCode Nerd Font
    style: Bold
 
  # The italic font face
  italic:
    family: Menlo
    style: Regular Italic
 
 # Point size of the font
  size: 14.0

debug:
  # Should display the render timer
  render_timer: false

# Mouse bindings
mouse:
  hide_when_typing: true

hints:
  enabled:
   - regex: "(ipfs:|ipns:|magnet:|mailto:|gemini:|gopher:|https:|http:|news:|file:|git:|ssh:|ftp:)\
             [^\u0000-\u001F\u007F-\u009F<>\"\\s{-}\\^⟨⟩`]+"
     hyperlinks: true
     command: xdg-open
     post_processing: true
     mouse:
       enabled: true
       mods: None
     binding:
       key: U
       mods: Control|Shift

selection:
  semantic_escape_chars: ",│`|:\"' ()[]{}<>"

  # When set to `true`, selected text will be copied to both the primary and
  # the selection clipboard. Otherwise, it will only be copied to the selection
  # clipboard.
  save_to_clipboard: true

# Cursor style
cursor:
  style: Block
  unfocused_hollow: false

# Live config reload (changes require restart)
live_config_reload: true

# Shell
# Entries in shell.args are passed unmodified as arguments to the shell.
shell:
  program: /usr/local/bin/fish
  args:
    - --login


# Key bindings
key_bindings:
  - { key: N, mods: Command, action: CreateNewWindow }
  - { key: Return,   mods: Command, action: ToggleSimpleFullscreen }
  - { key: V,        mods: Command, action: Paste                        }
  - { key: C,        mods: Command, action: Copy                         }
  - { key: Q,        mods: Command, action: Quit                         }
  - { key: N,        mods: Command, command: { program: "open", args: ["-nb", "io.alacritty"] } }
  - { key: Equals,   mods: Command, action: IncreaseFontSize             }
  - { key: Minus,    mods: Command, action: DecreaseFontSize             }
  - { key: W,        mods: Command,       chars: "\x04" }
  - { key: L,        mods: Command,       chars: "\x63\x6c\x65\x61\x72\x0a" } # Hex is equivalent to typing "clear"  
    # - { key: L,        mods: Command,       chars: "\x03\x63\x6c\x65\x61\x72\x0a" } # Hex is equivalent to typing "clear"  
  - { key: H,        mods: Command,       chars: "\x01\x1b\x5b\x44" }
  - { key: J,        mods: Command,       chars: "\x01\x1b\x5b\x42" }
  - { key: K,        mods: Command,       chars: "\x01\x1b\x5b\x41" }
  - { key: L,        mods: Command,       chars: "\x01\x1b\x5b\x43" }
  - { key: T,        mods: Command,       chars: "\x01\x63" }
  - { key: Tab,      mods: Shift,         chars: "\x01\x6e" }
  - { key: N,        mods: Alt,           chars: "\x01\x6e" }
  - { key: Key1,     mods: Command,       chars: "\x01\x30" }
  - { key: Key2,     mods: Command,       chars: "\x01\x31" }
  - { key: Key3,     mods: Command,       chars: "\x01\x32" }
  - { key: Key4,     mods: Command,       chars: "\x01\x33" }
  - { key: Key5,     mods: Command,       chars: "\x01\x34" }
  - { key: Key6,     mods: Command,       chars: "\x01\x35" }
  - { key: Key7,     mods: Command,       chars: "\x01\x36" }
  - { key: Key8,     mods: Command,       chars: "\x01\x37" }
  - { key: Key9,     mods: Command,       chars: "\x01\x38" }
  - { key: Key0,     mods: Command,       chars: "\x01\x39" }
  - { key: R,        mods: Command,       chars: "\x01\x7b" }
    #  - { key: Left,     mods: Command,       chars: "\x13\x1b\x5b\x44" }
    #  - { key: Down,     mods: Command,       chars: "\x13\x1b\x5b\x42" }
    #  - { key: Up,       mods: Command,       chars: "\x13\x1b\x5b\x41" }
    #  - { key: Right,    mods: Command,       chars: "\x13\x1b\x5b\x43" }
