# (r) = changes require application restart

# Environment Variables
env:
 TERM: xterm-256color

# Import color scheme
import:
- "~/.config/alacritty/color.yml"

window:
  # Window dimensions in character columns and lines (r)
  # dimensions:
  #   columns: 120
  #   lines: 61
  # position:
  #  x: 920
  #  y: 30

  # Startup Mode (changes require restart)
  # Values for `startup_mode`:
  #   - Windowed
  #   - Maximized
  #   - Fullscreen
  # Values for `startup_mode` (macOS only):
  #   - SimpleFullscreen
  startup_mode: Windowed 

  # Adds this many blank pixels of padding around the window
  # Units are physical pixels; this is not DPI aware.
  # (change requires restart)
  padding:
    x: 9
    y: 9

  # Spread additional padding evenly around the terminal content.
  dynamic_padding: true

  dynamic_title: true

  # Background opacity
  # opacity: 1
  opacity: 0.95

  # Window decoration
  # Full, Transparent, Buttonless, None
  decorations: None
  # decorations: None

# When true, bold text is drawn using the bright variant of colors.
draw_bold_text_with_bright_colors: true

scrolling:
  # Maximum number of lines in the scrollback buffer.
  history: 100000
  # Number of lines the viewport will move for every line scrolled when scrollback is enabled. 
  multiplier: 1

# Font configuration (changes require restart)
font:
 # The normal (roman) font face to use.
  normal:
    family: JetBrainsMono Nerd Font
    style: Regular
 
  # The bold font face
  bold:
    family: JetBrainsMono Nerd Font
    style: Bold
 
  # The italic font face
  italic:
    family: JetBrainsMono Nerd Font
    style: Italic
 
 # Point size of the font
  size: 19

debug:
  # Should display the render timer
  render_timer: false

# Mouse bindings
mouse:
  hide_when_typing: true

hints:
  enabled:
   - regex: "(ipfs:|ipns:|magnet:|mailto:|gemini:|gopher:|https:|http:|news:|file:|git:|ssh:|ftp:)\
             [^\u0000-\u001F\u007F-\u009F<>\"\\s{-}\\^⟨⟩`]+"
     hyperlinks: true
     command: xdg-open
     post_processing: true
     mouse:
       enabled: true
       mods: None
     binding:
       key: U
       mods: Control|Shift

selection:
  semantic_escape_chars: ",│`|:\"' ()[]{}<>"

  # When set to `true`, selected text will be copied to both the primary and
  # the selection clipboard. Otherwise, it will only be copied to the selection
  # clipboard.
  save_to_clipboard: true

# Cursor style
cursor:
  style: 
    shape: Block
  unfocused_hollow: false

# Live config reload (changes require restart)
live_config_reload: true

# Shell
# Entries in shell.args are passed unmodified as arguments to the shell.
shell:
  program: /usr/local/bin/fish
  args:
    - --login


# Key bindings
key_bindings:
  - { key: N, mods: Super, action: CreateNewWindow }
    # - { key: Return,   mods: Super, action: ToggleSimpleFullscreen }
  - { key: V,        mods: Super, action: Paste }
  - { key: C,        mods: Super, action: Copy }
  - { key: Q,        mods: Super, action: Quit }
    # - { key: N,        mods: Super, command: { program: "open", args: ["-nb", "io.alacritty"] } }
  - { key: Equals,   mods: Super, action: IncreaseFontSize }
  - { key: Minus,    mods: Super, action: DecreaseFontSize }
  - { key: W,        mods: Super,       chars: "\x04" }
  - { key: L,        mods: Super,       chars: "\x63\x6c\x65\x61\x72\x0a" } # Hex is equivalent to typing "clear"
    # - { key: L,        mods: Super,       chars: "\x03\x63\x6c\x65\x61\x72\x0a" } # Hex is equivalent to typing "clear"
  - { key: H,        mods: Super,       chars: "\x01\x1b\x5b\x44" }
  - { key: J,        mods: Super,       chars: "\x01\x1b\x5b\x42" }
  - { key: K,        mods: Super,       chars: "\x01\x1b\x5b\x41" }
  - { key: L,        mods: Super,       chars: "\x01\x1b\x5b\x43" }
  - { key: T,        mods: Super,       chars: "\x01\x63" }
  # - { key: Tab,      mods: Shift,         chars: "\x01\x6e" }
  - { key: N,        mods: Alt,           chars: "\x01\x6e" }
  - { key: Key0,     mods: Super,       chars: "\x01\x30" }
  - { key: Key1,     mods: Super,       chars: "\x01\x31" }
  - { key: Key2,     mods: Super,       chars: "\x01\x32" }
  - { key: Key3,     mods: Super,       chars: "\x01\x33" }
  - { key: Key4,     mods: Super,       chars: "\x01\x34" }
  - { key: Key5,     mods: Super,       chars: "\x01\x35" }
  - { key: Key6,     mods: Super,       chars: "\x01\x36" }
  - { key: Key7,     mods: Super,       chars: "\x01\x37" }
  - { key: Key8,     mods: Super,       chars: "\x01\x38" }
  - { key: Key9,     mods: Super,       chars: "\x01\x39" }
  - { key: R,        mods: Super,       chars: "\x01\x7b" }
  # Vi Mode
  - { key: Space,  mods: Shift|Control, mode: ~Search,    action: ToggleViMode            }
  - { key: Space,  mods: Shift|Control, mode: Vi|~Search, action: ScrollToBottom          }
  - { key: Escape,                      mode: Vi|~Search, action: ClearSelection          }
  - { key: I,                           mode: Vi|~Search, action: ToggleViMode            }
  - { key: I,                           mode: Vi|~Search, action: ScrollToBottom          }
  - { key: C,      mods: Control,       mode: Vi|~Search, action: ToggleViMode            }
  - { key: Y,      mods: Control,       mode: Vi|~Search, action: ScrollLineUp            }
  - { key: E,      mods: Control,       mode: Vi|~Search, action: ScrollLineDown          }
  - { key: G,                           mode: Vi|~Search, action: ScrollToTop             }
  - { key: G,      mods: Shift,         mode: Vi|~Search, action: ScrollToBottom          }
  - { key: B,      mods: Control,       mode: Vi|~Search, action: ScrollPageUp            }
  - { key: F,      mods: Control,       mode: Vi|~Search, action: ScrollPageDown          }
  - { key: U,      mods: Control,       mode: Vi|~Search, action: ScrollHalfPageUp        }
  - { key: D,      mods: Control,       mode: Vi|~Search, action: ScrollHalfPageDown      }
  - { key: Y,                           mode: Vi|~Search, action: Copy                    }
  - { key: Y,                           mode: Vi|~Search, action: ClearSelection          }
  - { key: Copy,                        mode: Vi|~Search, action: ClearSelection          }
  - { key: V,                           mode: Vi|~Search, action: ToggleNormalSelection   }
  - { key: V,      mods: Shift,         mode: Vi|~Search, action: ToggleLineSelection     }
  - { key: V,      mods: Control,       mode: Vi|~Search, action: ToggleBlockSelection    }
  - { key: V,      mods: Alt,           mode: Vi|~Search, action: ToggleSemanticSelection }
  - { key: Return,                      mode: Vi|~Search, action: Open                    }
  - { key: Z,                           mode: Vi|~Search, action: CenterAroundViCursor    }
  - { key: K,                           mode: Vi|~Search, action: Up                      }
  - { key: J,                           mode: Vi|~Search, action: Down                    }
  - { key: H,                           mode: Vi|~Search, action: Left                    }
  - { key: L,                           mode: Vi|~Search, action: Right                   }
  - { key: Up,                          mode: Vi|~Search, action: Up                      }
  - { key: Down,                        mode: Vi|~Search, action: Down                    }
  - { key: Left,                        mode: Vi|~Search, action: Left                    }
  - { key: Right,                       mode: Vi|~Search, action: Right                   }
  - { key: Key0,                        mode: Vi|~Search, action: First                   }
  - { key: Key4,   mods: Shift,         mode: Vi|~Search, action: Last                    }
  - { key: Key6,   mods: Shift,         mode: Vi|~Search, action: FirstOccupied           }
  - { key: H,      mods: Shift,         mode: Vi|~Search, action: High                    }
  - { key: M,      mods: Shift,         mode: Vi|~Search, action: Middle                  }
  - { key: L,      mods: Shift,         mode: Vi|~Search, action: Low                     }
  - { key: B,                           mode: Vi|~Search, action: SemanticLeft            }
  - { key: W,                           mode: Vi|~Search, action: SemanticRight           }
  - { key: E,                           mode: Vi|~Search, action: SemanticRightEnd        }
  - { key: B,      mods: Shift,         mode: Vi|~Search, action: WordLeft                }
  - { key: W,      mods: Shift,         mode: Vi|~Search, action: WordRight               }
  - { key: E,      mods: Shift,         mode: Vi|~Search, action: WordRightEnd            }
  - { key: Key5,   mods: Shift,         mode: Vi|~Search, action: Bracket                 }
  - { key: Slash,                       mode: Vi|~Search, action: SearchForward           }
  - { key: Slash,  mods: Shift,         mode: Vi|~Search, action: SearchBackward          }
  - { key: N,                           mode: Vi|~Search, action: SearchNext              }
  - { key: N,      mods: Shift,         mode: Vi|~Search, action: SearchPrevious          }
