require("clayton.plugin.autopairs")
require("clayton.plugin.color")
require("clayton.plugin.dap")
require("clayton.plugin.gitsigns")
require("clayton.plugin.go")
require("clayton.plugin.harpoon")
require("clayton.plugin.kiwi")
require("clayton.plugin.lsp")
require("clayton.plugin.lualine")
require("clayton.plugin.markdown")
-- require("clayton.plugin.noice")
require("clayton.plugin.nvim-cmp")
require("clayton.plugin.nvim-tree")
require("clayton.plugin.silicon")
require("clayton.plugin.telescope")
require("clayton.plugin.tex")
require("clayton.plugin.treesitter")
