#!/bin/sh
HOME="${HOME:?}"
XDG_CONFIG_HOME="${XDG_CONFIG_HOME:?}"
PWD=$(git rev-parse --show-toplevel)

if [ "$1" = "link" ]; then
    install_action="ln -svf"
    action_msg="Symlinking"
else
    install_action="cp -r"
    action_msg="Copying"
fi

ensure_paths() {
    # Ensure ~/.config path is available
    if [ ! -d "$HOME"/.config ]; then
        echo "Creating $HOME/.config directory..."
        mkdir "$HOME"/.config
    fi

    # Ensure ~/.local/bin path is available for install
    if [ ! -d "$HOME"/.local ]; then
        echo "Creating $HOME/.local directory..."
        mkdir "$HOME"/.local
        echo "Creating $HOME/.local/bin directory..."
        mkdir "$HOME"/.local/bin
    else
        if [ ! -d "$HOME"/.local/bin ]; then
            mkdir "$HOME"/.local/bin
        fi
    fi
}

remove_installation() {
    ./uninstall
}

install_executables() {
    # Softlink all executables in bin directory to ~/.local/bin
    printf "%s scripts/excecutables...\n" "$action_msg"
    find ./bin -maxdepth 1 -exec basename {} \; | sed 1d | while read -r file; do 
        eval "$install_action" "$PWD"/bin/"$file" "$HOME"/.local/bin/"$file"
    done
}

install_config () {
    # Install all directories in ./config to ~/.config
    printf "%s config folders...\n" "$action_msg"
    find ./config -maxdepth 1 -exec basename {} \; | sed 1d | while read -r dir; do 
        eval "$install_action" "$PWD"/config/"$dir" "$XDG_CONFIG_HOME/$dir"
    done

    # these should eventually be migrated to some sort of generic function
    eval "$install_action" "$PWD"/.bashrc "$HOME"/.bashrc
    mkdir "$HOME"/.hammerspoon
    eval "$install_action" "$PWD"/config/hammerspoon/init.lua "$HOME"/.hammerspoon/init.lua
}

main () {
    ensure_paths
    remove_installation
    install_config
    install_executables
    printf "Done!\n"
}

main
