#!/bin/sh
. ./bin/formatting.sh
. ./bin/vars.sh
DOTFILES_DIR="${DOTFILES_DIR:?}"

remove_installation() {
    info "Removing current config...\n"

    for executable in "$DOTFILES_DIR"/bin/*; do
        executable_target_path="${HOME:?}/.local/bin/${executable##*/}"
        if [ -e "$executable_target_path" ]; then
            rm -v "$executable_target_path";
        fi
    done

    for config in "$DOTFILES_DIR"/config/*; do
        config_target_path="${XDG_CONFIG_HOME:?}/${config##*/}"
        if [ -L "$config_target_path" ]; then
            rm -v "$config"
        elif [ -e "$config_target_path" ]; then
            rm -rv "$config";
        fi
    done

    if [ -e "$HOME"/.bashrc ]; then
        rm -v "$HOME"/.bashrc;
    fi
}

main() {
    remove_installation
    info "Finished removing existing config!\n"
}

main
