#!/bin/sh
DOTFILES_DIR="${DOTFILES_DIR:?}"
. "$DOTFILES_DIR"/formatting.sh

remove_installation() {
    info "Removing current config..."
    # Remove executables if they're installed
    find "$DOTFILES_DIR"/bin -maxdepth 1 -exec basename {} \; | sed 1d | while read -r file; do 
        if [ -e "${HOME:?}"/.local/bin/"$file" ]; then rm "${HOME:?}"/.local/bin/"$file"; fi
    done
    # Remove config directories if they're installed
    find "$DOTFILES_DIR"/config -maxdepth 1 -exec basename {} \; | sed 1d | while read -r dir; do 
        if [ -L "${XDG_CONFIG_HOME:?}"/"$dir" ]; then
            rm "${XDG_CONFIG_HOME:?}"/"$dir"
        else
            if [ -e "${XDG_CONFIG_HOME:?}"/"$dir" ]; then rm -r "${XDG_CONFIG_HOME:?}"/"$dir"; fi
        fi
    done

    if [ -e "$HOME"/.bashrc ]; then rm "$HOME"/.bashrc; fi
    if [ -e "$HOME"/.hammerspoon ]; then rm -r "$HOME"/.hammerspoon/; fi
}

main() {
    remove_installation
    info "Finished removing existing config!"
}

main

