#!/bin/sh
DOTFILES_DIR="${DOTFILES_DIR:?}"
. "$DOTFILES_DIR"/bin/formatting.sh

"$DARWIN_DIR"/configure-brew.sh
"$DARWIN_DIR"/configure-system.sh
"$DARWIN_DIR"/configure-apps.sh
# "$DARWIN_DIR"/configure-launchd.sh
