[colors.bright]
black = "#343d46"
blue = "#6699cc"
cyan = "#5fb3b3"
green = "#99C794"
magenta = "#c594c5"
red = "#EC5f67"
white = "#d8dee9"
yellow = "#FAC863"

[colors.cursor]
cursor = "#ffffff"
text = "#1b2b34"

[colors.normal]
black = "#343d46"
blue = "#6699cc"
cyan = "#5fb3b3"
green = "#99C794"
magenta = "#c594c5"
red = "#EC5f67"
white = "#d8dee9"
yellow = "#FAC863"

[colors.primary]
background = "#1b2b34"
foreground = "#d8dee9"

