[colors.bright]
black = "#434758"
blue = "#9cc4ff"
cyan = "#a3f7ff"
green = "#ddffa7"
magenta = "#e1acff"
red = "#ff8b92"
white = "#ffffff"
yellow = "#ffe585"

[colors.normal]
black = "#292d3e"
blue = "#82aaff"
cyan = "#89ddff"
green = "#c3e88d"
magenta = "#c792ea"
red = "#f07178"
white = "#d0d0d0"
yellow = "#ffcb6b"

[colors.primary]
background = "#292d3e"
foreground = "#d0d0d0"

